theme = "./themes/luna"

[siteConfig]
title = "庶民样本"
description = "EGOIST 在这里写作"
url = "https://egoist.moe"
author = "EGOIST"
email = "0x142857@gmail.com"

[themeConfig]
headerTitle = "e.z."
website = "https://github.com/egoist"
repo = "egoist/blog"
twitter = "_egoistlily"

  [[themeConfig.nav]]
  title = "about"
  link = "/about"

  [[themeConfig.nav]]
  title = "girls"
  link = "/girls"

  [[themeConfig.nav]]
  title = "donate"
  link = "/donate"

[markdown]
slugify = "./utils/slugify"
highlighter = "prism"

  [[markdown.plugins]]
  resolve = "markdown-it-footnote"

[permalinks]
page = "/:slug"
post = "/:year/:month/:day/:slug"

[[plugins]]
resolve = "saber-plugin-google-analytics"
  
  [plugins.options]
  trackId = "UA-54857209-6"