theme = "./themes/luna"

[siteConfig]
title = "庶民样本"
description = "EGOIST 在这里写作"
url = "https://egoist.moe"
author = "EGOIST"
email = "0x142857@gmail.com"
pwaFirstTimeInstallMessage = "本站可以离线访问"
pwaUpdateReadyMessage = "本站内容有更新"
pwaUpdateButtonMessage = "确认"
pwaDismissMessage = "忽略"

[themeConfig]
headerTitle = "echan"
website = "https://github.com/egoist"
repo = "egoist/blog"
twitter = "_egoistlily"

  [[themeConfig.nav]]
  title = "about"
  link = "/about"

  [[themeConfig.nav]]
  title = "girls"
  link = "/girls"

  [[themeConfig.nav]]
  title = "donate"
  link = "/donate"

[markdown]
slugify = "./utils/slugify"

  [[markdown.plugins]]
  resolve = "markdown-it-footnote"

[permalinks]
page = "/:slug"
post = "/:year/:month/:day/:slug"

[[plugins]]
resolve = "saber-plugin-google-analytics"
  
  [plugins.options]
  trackId = "UA-54857209-6"

[[plugins]]
resolve = "saber-plugin-feed"

  [plugins.options]
  atomFeed = true

[[plugins]]
# inject posts to / and generate tags page
# saber no longer does this automatically so we add this plugin
resolve = "saber-plugin-query-posts"

[[plugins]]
resolve = "saber-plugin-prismjs"

[[plugins]]
resolve = "saber-plugin-pwa"

[build]
lazy = true